# Generated by Django 2.2.9 on 2020-01-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
